# Generated by Django 5.2.5 on 2025-08-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='media_url',
        ),
        migrations.AddField(
            model_name='posts',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
