# Generated by Django 5.2.5 on 2025-08-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
