# Generated by Django 5.2.5 on 2025-08-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_commentlike'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
