# Generated by Django 5.2.5 on 2025-08-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_user_options_alter_user_managers_and_more'),
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.posts'),
        ),
    ]
